version: '3.9'
services:
  web:
    container_name: ${APP_NAME}
    image: trafex/php-nginx
    ports:
      - ${APP_DOCK_PORT}:8080
    volumes:
      - ./site:/var/www/html
      - ./server/etc/nginx:/etc/nginx
      - ./server/etc/php81:/etc/php81

