version: '3.9'
services:
  web:
    container_name: ${APP_NAME}
    image: trafex/php-nginx
    restart: unless-stopped
    ports:
      - ${APP_DOCK_PORT}:8080
    volumes:
      - ./site:/var/www/html
      - ./server/etc/nginx:/etc/nginx
      - ./server/etc/php81:/etc/php81
    networks:
      - backend
  pgsql:
    image: 'postgres:15'
    restart: unless-stopped
    ports:
      - '${DB_PORT}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - './data-pgsql:/var/lib/postgresql/data'
    networks:
      - backend
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '-q'
        - '-d'
        - 'postgres'
        - '-U'
        - 'dbmin'
      retries: 3
      timeout: 5s
networks:
  backend:
    driver: bridge
volumes:
  pgsql:
    driver: local
